name: serenique
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_fonts: ^6.1.0
  path_provider_windows: ^2.3.0
  path_provider_linux: ^2.2.1
  
  # Notification & Background Packages
  flutter_local_notifications: ^19.4.2
  workmanager: ^0.9.0+3 # ADD THIS PACKAGE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true